allowBuilds:
  "@tailwindcss/oxide": true
  esbuild: true
  workerd: true

# Supply chain security settings
blockExoticSubdeps: true
minimumReleaseAge: 360 # 6 hours
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver
  - tinyexec@1.2.2

pmOnFail: ignore
